classdef ExperimentViewer
    properties
        name
        subjectTab
        locations
        traces

        subjects_to_use logical
        filtered_traces

        dataFilter DataFilter
        plotConfig PlotConfig
    end

    methods (Static)
        function out = overlayMats(Marray)
            arguments
                Marray cell % cell array of 2D matrices to overlay
            end
            
            nrows = cellfun(@(x) size(x,1), Marray);
            ncols = cellfun(@(x) size(x,2), Marray);
            dimOut = [max(nrows), max(ncols)];
            
            n = numel(Marray);
            out = zeros(dimOut(1),dimOut(2), n);
            for i = 1:n
                thisM = Marray{i};
                out(1:size(thisM,1), 1:size(thisM,2), i) = thisM;
            end
        end
    end

    methods
        function obj = ExperimentViewer(experiment)
            arguments
                experiment Experiment
            end
            obj.name = experiment.name;
            obj.subjectTab = experiment.subjectTab;
            obj.locations = experiment.locations;
            obj.traces = experiment.traces(:);
            obj.dataFilter = DataFilter();
            obj.plotConfig = PlotConfig();
        end

        %% getters

        function idx = get.subjects_to_use(obj)
            subjectIDs = obj.dataFilter.getSubjectIDs(obj.subjectTab);
            idx = ismember(obj.subjectTab.name,subjectIDs);
        end

        function traces = get.filtered_traces(obj)
            % filter subjects
            traces = obj.traces(obj.subjects_to_use);
        end

        %% setters

        function obj = setTheme(obj, themeName)
            obj.plotConfig.theme = themeName;
        end
        
        %% intermediate-level plotting function headers 
        % (normally call external low level functions that don't rely on custom objects)
        % still output a single plot onto provided axes


        function out = plotBehavior2PTracesHead(obj, varargin)
            arguments
                obj
            end
            arguments (Repeating)
                varargin
            end

            [beh_traces, labs] = obj.dataFilter.filterData(obj);
            beh_traces = cellfun(@squeeze, beh_traces, 'UniformOutput', false);
            out = plotBehavior2PTraces(obj.dataFilter.interval, ...
                    beh_traces, labs, ...
                    obj.plotConfig, varargin{:});
        end


        function out = plotDistancesHead(obj, varargin)        
        % PLOTDISTANCESHEAD Plots distances between events in a 3D matrix.
        %
        %   out = plotDistancesHead(obj, varargin) generates a 3D distance matrix
        %   plot based on the events extracted from the object `obj`. The function
        %   allows customization of the plotting method and type through optional
        %   name-value pair arguments.
        %
        %   INPUTS:
        %       obj - The object containing the data and configuration for plotting.
        %
        %   OPTIONAL NAME-VALUE PAIR ARGUMENTS:
        %       'method'   - (string) The method used to compute distances. Default
        %                    is 'correlation'.
        %       'plotType' - (string) The type of plot to generate. Default is 'full'.
        %
        %   OUTPUT:
        %       out - A structure containing the following fields:
        %           distMat3d - The 3D distance matrix generated by the plot.
        %           all_labs  - Cell array of labels for all subjects.
        %
        %   NOTES:
        %       - The function checks for consistency in labels across subjects. If
        %         labels differ, a warning is issued, and mock labels are generated.
        %       - The title of the plot includes the time interval used for filtering
        %         the data.
        %
        %   EXAMPLE USAGE:
        %       obj = ExperimentViewer(); % Assuming ExperimentViewer is a class
        %       out = obj.plotDistancesHead('method', 'euclidean', 'plotType', 'repetitions');
        %
        %   See also: ModeSelector, plotDistances
            arguments
                obj
            end
            arguments (Repeating)
                varargin
            end

            % Set default values
            plotType = 'full';
            method = 'correlation';

            % Parse name-value pairs
            if ~isempty(varargin)
                for k = 1:2:length(varargin)
                    switch lower(varargin{k})
                        % processing parameters
                        case 'method'
                            method = varargin{k+1};
                        % plotting parameters
                        case 'plottype'
                            plotType = varargin{k+1};
                    end
                end
            end

            % initialize output
            out = [];
            
            % Isolating relevant data
            dft = obj.dataFilter;
            [~, events, all_labs] = ModeSelector(obj).extract;
            if all(cellfun(@isempty,events)); return; end

            % by default, labels are applied based on subject 1
            labs = all_labs{1};

            % Check that all label arrays are the same. This can happen
            % when filtering stimuli according to other properties than
            % identity (ex. trained/novel) from multiple experimental
            % groups.
            all_equal = all(cellfun(@(x) isequal(x, labs), all_labs));
            if ~all_equal
                warning('Mock labels! Actual stimulus identities differ across subjects!')
                % Replace labs with mock labels following the identity structure in labs{1}
                [~, ~, ic] = unique(labs, 'stable');
                mockLabels = arrayfun(@(x) char('A' + x - 1), ic, 'UniformOutput', false);
                labs = mockLabels;
            end

            % call low-level plotter
            out.distMat3d = plotDistances(events,plotType,method,labs,obj.plotConfig);
            ps_lim = dft.interval; % actual interval used
            title([num2str(ps_lim(1)),'-',num2str(ps_lim(2)), ' s'], ...
                'Color',obj.plotConfig.textcol)

            % return
            out.all_labs = all_labs;

        end


        function out = plotDiscriminationHead(obj, varargin)
        % PLOTDISCRIMINATIONHEAD Plots discrimination analysis results for the given object.
        %
        %   out = plotDiscriminationHead(obj, varargin) performs discrimination 
        %   analysis and generates a plot based on the specified parameters.
        %
        %   INPUTS:
        %       obj - The object containing the data and configuration for the analysis.
        %
        %   NAME-VALUE PAIR ARGUMENTS:
        %       'method'       - (string) The method used for discrimination analysis. 
        %                        Default is 'correlation'.
        %       'plotType'     - (string) The type of plot to generate. 
        %                        Default is 'performance_lines'.
        %       'focus_stims'  - (string) Specifies the stimuli to focus on for plotting. 
        %                        Default is 'all trials'.
        %       'zscore'       - (logical) Whether to apply z-scoring to the data. 
        %                        Default is false.
        %
        %   OUTPUT:
        %       out - The output of the plotDiscrimination function, which contains 
        %             the generated plot and associated data.
        %
        %   DESCRIPTION:
        %       This function performs discrimination analysis on the data contained 
        %       in the input object. It allows for customization of the analysis 
        %       method, plot type, and stimuli focus through name-value pair arguments. 
        %       The function filters and processes the data, performs the analysis, 
        %       and generates the specified plot.
        %
        %   EXAMPLES:
        %       % Example 1: Basic usage with default parameters
        %       out = obj.plotDiscriminationHead();
        %
        %       % Example 2: Custom method and plot type
        %       out = obj.plotDiscriminationHead('method', 'euclidean', 'plotType', 'bar');
        %
        %       % Example 3: Focus on specific stimuli and apply z-scoring
        %       out = obj.plotDiscriminationHead('focus_stims', 'stimulus_A', 'zscore', true);
        %
        %   NOTES:
        %       - The function skips subjects with empty data or no allowed stimuli.
        %       - The low-level processing and plotting are handled by the 
        %         doDiscrimination and plotDiscrimination functions, respectively.
        %
        %   See also: doDiscrimination, plotDiscrimination, getStimuliByGroup
            arguments
                obj
            end
            arguments (Repeating)
                varargin
            end

            % Set default values
            plotType = 'performance_lines';
            method = 'correlation';
            focus_stims = 'all trials'; % by default, no further filtering
            do_zscore = false;

            % Parse name-value pairs
            if ~isempty(varargin)
                for k = 1:2:length(varargin)
                    switch lower(varargin{k})
                        % processing parameters
                        case 'method'
                            method = varargin{k+1};
                        % plotting parameters
                        case 'plottype'
                            plotType = varargin{k+1};
                        case 'focus_stims'
                            focus_stims = varargin{k+1};
                        case 'zscore'
                            do_zscore = varargin{k+1};
                    end
                end
            end

            % initialize output
            out = [];
            
            % Isolating relevant data
            dft = obj.dataFilter;
            [~, events, all_labs] = ModeSelector(obj).extract;
            if all(cellfun(@isempty,events)); return; end

            % useful metrics
            nsubjects = numel(obj.filtered_traces);

            % call low-level processor (perform discrimination analysis)
            all_out = cell(nsubjects,1);
            for i = 1:nsubjects
                thisevents = events{i};
                thislabs = all_labs{i};

                % if there are no allowed stimuli here, skip subject
                if isempty(thislabs); continue; end

                % call post-processing function
                all_out{i} = doDiscrimination(thisevents, thislabs, ...
                                                       'method', method);
            end

            % focus on specific trials for plotting (without changing any of the values!)
            focus_trials = cell(nsubjects,1);
            for i = 1:nsubjects
                thistrace = obj.filtered_traces{i};
                thisgroup = thistrace.subject_group;
                desired_stimuli = getStimuliByGroup(thisgroup,focus_stims);
                idx = ismember(all_labs{i}, desired_stimuli);
                focus_trials{i} = find(idx);
            end

            % get rid of empty data
            idx = cellfun(@isempty,all_out) | cellfun(@isempty,focus_trials);
            all_out(idx) = [];
            focus_trials(idx) = [];
            if isempty(all_out); return; end

            % call low-level plotter
            out = plotDiscrimination(all_out,...
                plotType,obj.plotConfig, ...
                'method',method, ...
                'FocusTrials',focus_trials, ...
                'actualreps', dft.repetitions, ...
                'zscore',do_zscore);

            % return

        end



        function out = plotTrialActivityMetricHead(obj, varargin)
        % PLOTTRIALACTIVITYMETRICHEAD Plots activity metrics for trial data.
        %
        %   out = PLOTTRIALACTIVITYMETRICHEAD(obj, varargin) processes and plots
        %   activity metrics for trial data using the specified method and plot type.
        %
        %   INPUTS:
        %       obj - The object containing the data and configuration for plotting.
        %
        %   NAME-VALUE PAIR ARGUMENTS:
        %       'method'    - (string) The method used to calculate the activity metric.
        %                     Default is 'participation ratio'.
        %       'n_equals'  - (string) Specifies the normalization method for the metric.
        %                     Default is 'cells'.
        %       'plotType'  - (string) The type of plot to generate. Default is 'boxplot'.
        %       'normalize' - (logical) Whether to normalize the data before plotting.
        %                     Default is false.
        %
        %   OUTPUT:
        %       out - The output of the plotting function, which depends on the
        %             implementation of the low-level plotter.
        %
        %   DESCRIPTION:
        %       This function processes trial data to compute activity metrics using
        %       the specified method. It then generates a plot of the metrics using
        %       the specified plot type. The function supports optional normalization
        %       of the data. The data is filtered and processed before plotting, and
        %       empty data is excluded from the analysis.
        %
        %   EXAMPLE USAGE:
        %       obj = ExperimentViewer();
        %       out = obj.plotTrialActivityMetricHead('method', 'participation ratio', ...
        %                                             'plotType', 'boxplot', ...
        %                                             'normalize', true);
        %
        %   See also: extractActivityMetric, plotTrialMetric
            arguments
                obj
            end
            arguments (Repeating)
                varargin
            end

            % Set default values
            plotType = 'boxplot';
            method = 'participation ratio';
            n_equals = 'cells';
            do_normalize = false;

            % Parse name-value pairs
            if ~isempty(varargin)
                for k = 1:2:length(varargin)
                    switch lower(varargin{k})
                        % processing parameters
                        case 'method'
                            method = varargin{k+1};
                        case 'n_equals'
                            n_equals = varargin{k+1};
                        % plotting parameters
                        case 'plottype'
                            plotType = varargin{k+1};
                        case 'normalize'
                            do_normalize = varargin{k+1};
                    end
                end
            end

            % initialize output
            out = [];
            
            % Isolating relevant data
            dft = obj.dataFilter;
            obj.dataFilter.repetitions = []; % always use all repetitions
            [~, events, all_labs] = ModeSelector(obj).extract;
            obj.dataFilter = dft; % restore
            if all(cellfun(@isempty,events)); return; end

            % useful metrics
            nsubjects = numel(obj.filtered_traces);

            % call low-level processor (perform discrimination analysis)
            all_out = cell(nsubjects,1);
            for i = 1:nsubjects
                thisevents = events{i};

                % call post-processing function
                all_out{i} = extractActivityMetric(thisevents, method, n_equals);
            end

            % get rid of empty data
            idx = cellfun(@isempty,all_out);
            all_out(idx) = [];
            if isempty(all_out); return; end

            % if output metrics are not 1D, assume that the last available dimension is trials
            for i = 1:numel(all_out)
                sz = size(all_out{i});
                if numel(sz) > 1 && sz(end) > 1
                    % average along all other dimensions except the last (trials)
                    dims_to_avg = 1:(numel(sz)-1);
                    all_out{i} = squeeze(mean(all_out{i}, dims_to_avg));
                    % ensure column vector
                    if isrow(all_out{i})
                        all_out{i} = all_out{i}';
                    end
                end
            end

            % call low-level plotter
            out = plotTrialMetric(all_out,...
                plotType, all_labs, ...
                do_normalize, obj.plotConfig);

            % return

        end



        function out = plotUnitActivityMetricHead(obj, varargin)
        % PLOTUNITACTIVITYMETRICHEAD Plots unit activity metrics for experimental data.
        %
        %   OUT = PLOTUNITACTIVITYMETRICHEAD(OBJ, VARARGIN) processes and visualizes
        %   unit activity metrics based on the provided experimental data. The function
        %   supports various methods for processing and plotting the data.
        %
        %   INPUTS:
        %       OBJ - The object containing experimental data and methods for processing.
        %
        %   OPTIONAL NAME-VALUE PAIR ARGUMENTS:
        %       'method'   - (string) Specifies the method for processing activity metrics.
        %                    Default is 'tuning curves'.
        %       'n_equals' - (string) Specifies the normalization method for cells.
        %                    Default is 'cells'.
        %       'plotType' - (string) Specifies the type of plot to generate.
        %                    Default is 'boxplot'.
        %
        %   OUTPUT:
        %       OUT - A cell array containing processed activity metrics for each subject.
        %             If no valid data is available, the function returns an empty array.
        %
        %   DESCRIPTION:
        %       The function isolates relevant data from the provided object, processes
        %       the data using the specified method, and generates plots based on the
        %       selected plot type. It handles multiple subjects and filters out empty
        %       or invalid data. The processed data is returned as output.
        %
        %   EXAMPLES:
        %       % Example 1: Default usage
        %       out = obj.plotUnitActivityMetricHead();
        %
        %       % Example 2: Custom method and plot type
        %       out = obj.plotUnitActivityMetricHead('method', 'spike rates', 'plotType', 'scatter');
        %
        %   NOTE:
        %       This function requires the ModeSelector and extractActivityMetric
        %       methods to be implemented in the object.
            arguments
                obj
            end
            arguments (Repeating)
                varargin
            end

            % Set default values
            plotType = 'boxplot';
            method = 'tuning curves';
            n_equals = 'cells';

            % Parse name-value pairs
            if ~isempty(varargin)
                for k = 1:2:length(varargin)
                    switch lower(varargin{k})
                        % processing parameters
                        case 'method'
                            method = varargin{k+1};
                        case 'n_equals'
                            n_equals = varargin{k+1};
                        % plotting parameters
                        case 'plottype'
                            plotType = varargin{k+1};
                    end
                end
            end

            % initialize output
            out = [];
            
            % Isolating relevant data
            [~, events, all_labs] = ModeSelector(obj).extract;
            if all(cellfun(@isempty,events)); return; end

            % useful metrics
            nsubjects = numel(obj.filtered_traces);

            % call low-level processor
            all_out = cell(nsubjects,1);
            for i = 1:nsubjects
                thisevents = events{i};
                thislabs = all_labs{i};

                % if there are no allowed stimuli here, skip subject
                if isempty(thislabs); continue; end

                % call post-processing function
                all_out{i} = extractActivityMetric(thisevents, method, n_equals, ...
                    'StimTypes', thislabs);
            end

            % get rid of empty data
            idx = cellfun(@isempty,all_out);
            all_out(idx) = [];
            if isempty(all_out); return; end

            % call low-level plotter

            % return
            out = all_out;

        end

        %% complex and idiosyncratic high-level plotters are saved in external files


    end
end