function [b, params] = prettyBoxplot(dataMat, labs, varargin)
arguments
    dataMat double
    labs cell = {''}
end
arguments (Repeating)
    varargin
end

params = paramsStruct();
for k = 1:2:length(varargin)
    paramName = varargin{k};
    paramValue = varargin{k+1};
    if isfield(params, paramName)
        params.(paramName) = paramValue;
    else
        error('Unknown parameter name: %s', paramName);
    end

end

[nvars, nmeas] = size(dataMat);

b(1) = boxchart(dataMat, ...
    'Orientation', params.orientation, ...
    'BoxFaceColor', params.boxColor, ...
    'MarkerStyle', params.outlierStyle, ...
    'MarkerSize', params.outlierSize);

xticklabels(labs);
hold on

b(2) = scatter(1:nmeas,mean(dataMat,'omitmissing'), ...
    params.scatterSize, ...
    params.scatterColor,'filled');

box off;

if ~params.plotLine; return; end

b(3) = plot([0 nmeas+1],params.lineVal * [1 1], ...
    'LineWidth', params.lineWidth, ...
    'Color', params.lineColor, ...
    'LineStyle', params.lineStyle);

end

function params = paramsStruct()
params = struct(...
    'orientation', 'vertical', ...
    'boxColor', [0 0 0], ...
    'outlierStyle', 'none', ...
    'outlierSize', 6, ...
    ...
    'scatterColor', [1 0 0], ...
    'scatterSize', 36, ...
    'scatterMarker', 'o', ...
    ...
    'plotLine', false, ...
    'lineVal', 0, ...
    'lineWidth', 1.5, ...
    'lineColor', [1 0 0], ...
    'lineStyle', '--' ...
    );
end