function desired_stimuli = getStimuliByGroup(group,tag)
    
    if iscell(tag) % If tag already contains an array of stimuli
        desired_stimuli = tag;
        return
    end

    % Selects stimuli based on group and tag (single subject!)
    all_groups = {'previousnaive';'naïve';'trained1';'trained2';'trained1 (T-R-S-H-A-ACSF/L)';'uncoupled'};
    all_trials = {{'baseline','noodor','ACSF','Trp','Ala','Ser','Food'}; ...
        {'spont.','ACSF','Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'spont.','ACSF','Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'spont.','ACSF','Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'spont.','ACSF','Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'spont.','ACSF','Arg','Ala','His','Trp','Ser','Leu'}};
    all_stims = {{'Trp','Ala','Ser','Food'}; ...
        {'Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'Arg','Ala','His','Trp','Ser','Leu'}; ...
        {'Arg','Ala','His','Trp','Ser','Leu'}};
    all_CSplus = {{''};{''};{'Arg','Ala'};{'Ala','His'};{'Arg','Ala'};{''}};
    all_CSminus = {{''};{''};{'His'};{'Arg'};{'His'};{}};
    all_familiar = {{''};{''};{'Arg','Ala','His'};{'Arg','Ala','His'};{'Arg','Ala','His'};{'Arg','Ala','His'}}; % CS+ and CS- together
    all_novel = {{'Trp','Ala','Ser','Food'};{'Trp','Ser','Leu'};{'Trp','Ser','Leu'};{'Trp','Ser','Leu'};{'Trp','Ser','Leu'};{'Trp','Ser','Leu'}};
    
    groups2stims = table(all_groups, ...
                         all_trials, ...
                         all_stims, ...
                         all_CSplus, ...
                         all_CSminus, ...
                         all_familiar, ...
                         all_novel);
    
    group_idx = ismember(groups2stims.all_groups,group);
    switch tag
        case 'all trials'
            desired_stimuli = groups2stims.all_trials{group_idx};
        case 'all stimuli'
            desired_stimuli = groups2stims.all_stims{group_idx};
        case 'all CS+'
            desired_stimuli = groups2stims.all_CSplus{group_idx};
        case 'all CS-'
            desired_stimuli = groups2stims.all_CSminus{group_idx};               
        case 'all familiar'
            desired_stimuli = groups2stims.all_familiar{group_idx};
        case 'all novel'
            desired_stimuli = groups2stims.all_novel{group_idx};
        otherwise
            error('stimulus group tag invalid.')
    end
end